"""Project-wide settings for Neon Grove."""

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FPS = 60

CELL_SIZE = 24
GRID_WIDTH = WINDOW_WIDTH // CELL_SIZE
GRID_HEIGHT = WINDOW_HEIGHT // CELL_SIZE

STARTING_MOVE_INTERVAL = 0.14
MIN_MOVE_INTERVAL = 0.07
SPEEDUP_PER_FOOD = 0.003

START_LENGTH = 4
WINDOW_TITLE = "Neon Grove"
